FROM node:15-alpine

WORKDIR /app

COPY . .

RUN npm i --silent

RUN npm run build 



FROM keymetrics/pm2:15-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY --from=0 /app/dist /app/dist/
COPY ["package.json", "swagger.yaml", "ecosystem.yml", "./"]

RUN npm i --silent

CMD pm2-runtime start ecosystem.yml
